/* Generated By:JJTree: Do not edit this line. ASTEqualEqualExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package lab1;

public
class ASTEqualEqualExp extends SimpleNode {
  public ASTEqualEqualExp(int id) {
    super(id);
  }

  public ASTEqualEqualExp(Grammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(GrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9f1e9fe2b1e7b337d242aaed46ca77ef (do not edit this line) */
